# Generated by Django 2.1.7 on 2019-03-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=4, verbose_name='LED State')),
                ('updated_date', models.DateTimeField(verbose_name='Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=4, verbose_name='Room Temperature')),
                ('updated_date', models.DateTimeField(verbose_name='Updated Date')),
            ],
        ),
    ]
