# Generated by Django 2.1.7 on 2019-03-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=4, verbose_name='LED State')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor1Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=10, verbose_name='Sensor name')),
                ('state', models.CharField(max_length=4, verbose_name='LED State')),
                ('time', models.CharField(max_length=35, verbose_name='time instant')),
            ],
        ),
    ]
