# Generated by Django 2.1.7 on 2019-03-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Sensor2',
        ),
    ]
