# Generated by Django 2.1.7 on 2019-03-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_sensor1_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor1Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=10, verbose_name='Sensor name')),
                ('state', models.CharField(max_length=4, verbose_name='LED State')),
                ('time', models.CharField(max_length=10, verbose_name='time instant')),
            ],
        ),
    ]
